version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bl0ck$1234
    ports:
      - "1433:1433"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Bl0ck$1234", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
