name: Backend - Build en Integratietests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Bouw backend-oplossing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Herstel dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

  integration-tests:
    name: Draai integratietests
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Herstel dependencies
        run: dotnet restore

      - name: Draai tests en genereer .trx
        run: dotnet test backend.Tests/backend.Tests.csproj --configuration Release --no-build --logger "trx"

      - name: Upload testresultaten (.trx)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
