name: Backend Integratietests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository ophalen
        uses: actions/checkout@v3

      - name: .NET 9 installeren
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Dependencies herstellen
        run: dotnet restore

      - name: Project bouwen
        run: dotnet build --configuration Release --no-restore

      - name: Integratietests uitvoeren
        run: dotnet test backend.Tests/backend.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Testresultaten uploaden
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'
